// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wkkbpcmrhrrsuirlsxsn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indra2JwY21yaHJyc3VpcmxzeHNuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0NjgxMTUsImV4cCI6MjA2NzA0NDExNX0.99QQ65jKdDskIzgxjoijY8NWVqXOFMk0WLgIFTFjrqM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});